# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bucpa\OneDrive\Documents\eclipse\workspace\splendor_ai\splendor_ui\gem_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1268, 547)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 1171, 355))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.gemsAvailableTable = GemTableView(self.layoutWidget)
        self.gemsAvailableTable.setObjectName("gemsAvailableTable")
        self.verticalLayout_12.addWidget(self.gemsAvailableTable)
        self.verticalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.gemDialogButtons = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.gemDialogButtons.setOrientation(QtCore.Qt.Horizontal)
        self.gemDialogButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.gemDialogButtons.setObjectName("gemDialogButtons")
        self.verticalLayout_7.addWidget(self.gemDialogButtons)

        self.retranslateUi(Dialog)
        self.gemDialogButtons.accepted.connect(Dialog.accept) # type: ignore
        self.gemDialogButtons.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Gems:"))
from view.widgets.GemTableView import GemTableView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
