# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bucpa\OneDrive\Documents\eclipse\workspace\splendor_ai\splendor_ui\gem_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(603, 500)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 561, 355))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.gemWithdrawTable = GemTableView(self.layoutWidget)
        self.gemWithdrawTable.setMidLineWidth(1)
        self.gemWithdrawTable.setAutoScrollMargin(19)
        self.gemWithdrawTable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.gemWithdrawTable.setObjectName("gemWithdrawTable")
        self.gemWithdrawTable.horizontalHeader().setMinimumSectionSize(52)
        self.verticalLayout_6.addWidget(self.gemWithdrawTable)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.whiteLabel = QtWidgets.QLabel(self.layoutWidget)
        self.whiteLabel.setObjectName("whiteLabel")
        self.verticalLayout.addWidget(self.whiteLabel)
        self.whiteGemInput = QtWidgets.QSpinBox(self.layoutWidget)
        self.whiteGemInput.setObjectName("whiteGemInput")
        self.verticalLayout.addWidget(self.whiteGemInput)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.blueGemInput = QtWidgets.QSpinBox(self.layoutWidget)
        self.blueGemInput.setObjectName("blueGemInput")
        self.verticalLayout_2.addWidget(self.blueGemInput)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.greenGemInput = QtWidgets.QSpinBox(self.layoutWidget)
        self.greenGemInput.setObjectName("greenGemInput")
        self.verticalLayout_3.addWidget(self.greenGemInput)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.redGemInput = QtWidgets.QSpinBox(self.layoutWidget)
        self.redGemInput.setObjectName("redGemInput")
        self.verticalLayout_4.addWidget(self.redGemInput)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.blackGemInput = QtWidgets.QSpinBox(self.layoutWidget)
        self.blackGemInput.setObjectName("blackGemInput")
        self.verticalLayout_5.addWidget(self.blackGemInput)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.gemDialogButtons = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.gemDialogButtons.setOrientation(QtCore.Qt.Horizontal)
        self.gemDialogButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.gemDialogButtons.setObjectName("gemDialogButtons")
        self.verticalLayout_7.addWidget(self.gemDialogButtons)

        self.retranslateUi(Dialog)
        self.gemDialogButtons.accepted.connect(Dialog.accept) # type: ignore
        self.gemDialogButtons.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Gems to withdraw:"))
        self.label_6.setText(_translate("Dialog", "available:"))
        self.whiteLabel.setText(_translate("Dialog", "white"))
        self.label_2.setText(_translate("Dialog", "blue"))
        self.label_3.setText(_translate("Dialog", "green"))
        self.label_4.setText(_translate("Dialog", "red"))
        self.label_5.setText(_translate("Dialog", "black"))
from view.widgets.GemTableView import GemTableView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
