# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bucpa\OneDrive\Documents\eclipse\workspace\splendor_ai\splendor_ui\noble_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GemDialog(object):
    def setupUi(self, GemDialog):
        GemDialog.setObjectName("GemDialog")
        GemDialog.resize(1268, 547)
        self.layoutWidget = QtWidgets.QWidget(GemDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 1171, 355))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.noblesAvailableTable = QtWidgets.QTableView(self.layoutWidget)
        self.noblesAvailableTable.setObjectName("noblesAvailableTable")
        self.verticalLayout_12.addWidget(self.noblesAvailableTable)
        self.verticalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.nobleDialogButtons = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.nobleDialogButtons.setOrientation(QtCore.Qt.Horizontal)
        self.nobleDialogButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.nobleDialogButtons.setObjectName("nobleDialogButtons")
        self.verticalLayout_7.addWidget(self.nobleDialogButtons)

        self.retranslateUi(GemDialog)
        self.nobleDialogButtons.accepted.connect(GemDialog.accept) # type: ignore
        self.nobleDialogButtons.rejected.connect(GemDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GemDialog)

    def retranslateUi(self, GemDialog):
        _translate = QtCore.QCoreApplication.translate
        GemDialog.setWindowTitle(_translate("GemDialog", "Dialog"))
        self.label_6.setText(_translate("GemDialog", "Available Nobles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GemDialog = QtWidgets.QDialog()
    ui = Ui_GemDialog()
    ui.setupUi(GemDialog)
    GemDialog.show()
    sys.exit(app.exec_())
